/**
 * Wilaya names in the three languages, for the push titles.
 *
 * GENERATED from packages/core/src/wilayas.ts — do not edit by hand. Run
 * `node supabase/functions/send-push/wilayas.generate.mjs` after changing that
 * table; packages/core/src/wilayaLabels.test.ts fails while the two disagree.
 *
 * Keyed by the canonical French name, which is what blood_requests.wilaya
 * stores ("Alger", never "Algiers" or "16").
 */
export const WILAYA_LABELS: Record<string, { en: string; fr: string; ar: string }> = {
  "Adrar": { en: "Adrar", fr: "Adrar", ar: "أدرار" },
  "Chlef": { en: "Chlef", fr: "Chlef", ar: "الشلف" },
  "Laghouat": { en: "Laghouat", fr: "Laghouat", ar: "الأغواط" },
  "Oum El Bouaghi": { en: "Oum El Bouaghi", fr: "Oum El Bouaghi", ar: "أم البواقي" },
  "Batna": { en: "Batna", fr: "Batna", ar: "باتنة" },
  "Béjaïa": { en: "Béjaïa", fr: "Béjaïa", ar: "بجاية" },
  "Biskra": { en: "Biskra", fr: "Biskra", ar: "بسكرة" },
  "Béchar": { en: "Béchar", fr: "Béchar", ar: "بشار" },
  "Blida": { en: "Blida", fr: "Blida", ar: "البليدة" },
  "Bouira": { en: "Bouira", fr: "Bouira", ar: "البويرة" },
  "Tamanrasset": { en: "Tamanrasset", fr: "Tamanrasset", ar: "تمنراست" },
  "Tébessa": { en: "Tébessa", fr: "Tébessa", ar: "تبسة" },
  "Tlemcen": { en: "Tlemcen", fr: "Tlemcen", ar: "تلمسان" },
  "Tiaret": { en: "Tiaret", fr: "Tiaret", ar: "تيارت" },
  "Tizi Ouzou": { en: "Tizi Ouzou", fr: "Tizi Ouzou", ar: "تيزي وزو" },
  "Alger": { en: "Algiers", fr: "Alger", ar: "الجزائر" },
  "Djelfa": { en: "Djelfa", fr: "Djelfa", ar: "الجلفة" },
  "Jijel": { en: "Jijel", fr: "Jijel", ar: "جيجل" },
  "Sétif": { en: "Sétif", fr: "Sétif", ar: "سطيف" },
  "Saïda": { en: "Saïda", fr: "Saïda", ar: "سعيدة" },
  "Skikda": { en: "Skikda", fr: "Skikda", ar: "سكيكدة" },
  "Sidi Bel Abbès": { en: "Sidi Bel Abbès", fr: "Sidi Bel Abbès", ar: "سيدي بلعباس" },
  "Annaba": { en: "Annaba", fr: "Annaba", ar: "عنابة" },
  "Guelma": { en: "Guelma", fr: "Guelma", ar: "قالمة" },
  "Constantine": { en: "Constantine", fr: "Constantine", ar: "قسنطينة" },
  "Médéa": { en: "Médéa", fr: "Médéa", ar: "المدية" },
  "Mostaganem": { en: "Mostaganem", fr: "Mostaganem", ar: "مستغانم" },
  "M'Sila": { en: "M'Sila", fr: "M'Sila", ar: "المسيلة" },
  "Mascara": { en: "Mascara", fr: "Mascara", ar: "معسكر" },
  "Ouargla": { en: "Ouargla", fr: "Ouargla", ar: "ورقلة" },
  "Oran": { en: "Oran", fr: "Oran", ar: "وهران" },
  "El Bayadh": { en: "El Bayadh", fr: "El Bayadh", ar: "البيض" },
  "Illizi": { en: "Illizi", fr: "Illizi", ar: "إليزي" },
  "Bordj Bou Arréridj": { en: "Bordj Bou Arréridj", fr: "Bordj Bou Arréridj", ar: "برج بوعريريج" },
  "Boumerdès": { en: "Boumerdès", fr: "Boumerdès", ar: "بومرداس" },
  "El Tarf": { en: "El Tarf", fr: "El Tarf", ar: "الطارف" },
  "Tindouf": { en: "Tindouf", fr: "Tindouf", ar: "تندوف" },
  "Tissemsilt": { en: "Tissemsilt", fr: "Tissemsilt", ar: "تيسمسيلت" },
  "El Oued": { en: "El Oued", fr: "El Oued", ar: "الوادي" },
  "Khenchela": { en: "Khenchela", fr: "Khenchela", ar: "خنشلة" },
  "Souk Ahras": { en: "Souk Ahras", fr: "Souk Ahras", ar: "سوق أهراس" },
  "Tipaza": { en: "Tipaza", fr: "Tipaza", ar: "تيبازة" },
  "Mila": { en: "Mila", fr: "Mila", ar: "ميلة" },
  "Aïn Defla": { en: "Aïn Defla", fr: "Aïn Defla", ar: "عين الدفلى" },
  "Naâma": { en: "Naâma", fr: "Naâma", ar: "النعامة" },
  "Aïn Témouchent": { en: "Aïn Témouchent", fr: "Aïn Témouchent", ar: "عين تموشنت" },
  "Ghardaïa": { en: "Ghardaïa", fr: "Ghardaïa", ar: "غرداية" },
  "Relizane": { en: "Relizane", fr: "Relizane", ar: "غليزان" },
  "Timimoun": { en: "Timimoun", fr: "Timimoun", ar: "تيميمون" },
  "Bordj Badji Mokhtar": { en: "Bordj Badji Mokhtar", fr: "Bordj Badji Mokhtar", ar: "برج باجي مختار" },
  "Ouled Djellal": { en: "Ouled Djellal", fr: "Ouled Djellal", ar: "أولاد جلال" },
  "Béni Abbès": { en: "Béni Abbès", fr: "Béni Abbès", ar: "بني عباس" },
  "In Salah": { en: "In Salah", fr: "In Salah", ar: "عين صالح" },
  "In Guezzam": { en: "In Guezzam", fr: "In Guezzam", ar: "عين قزام" },
  "Touggourt": { en: "Touggourt", fr: "Touggourt", ar: "تقرت" },
  "Djanet": { en: "Djanet", fr: "Djanet", ar: "جانت" },
  "El M'Ghair": { en: "El M'Ghair", fr: "El M'Ghair", ar: "المغير" },
  "El Meniaa": { en: "El Meniaa", fr: "El Meniaa", ar: "المنيعة" },
};
